FROM registry.cn-hangzhou.aliyuncs.com/choerodon-tools/javabase:0.8.0
WORKDIR /choerodon
COPY app.jar hrds-code-repo.jar
COPY dist dist
RUN chmod +x /choerodon/dist/env.sh \
    && chown -R www-data:www-data /choerodon
USER www-data
CMD /choerodon/dist/env.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /choerodon/hrds-code-repo.jar